name: Publish NuGet Package

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'
        
    - name: Get version from tag
      id: get_version
      run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --configuration Release --no-restore
      
    - name: Test
      run: dotnet test UnitTest/UnitTest.csproj --no-restore --verbosity normal
      
    - name: Copy DLL and PDB to Unity package
      run: |
        cp NetProject/bin/Release/netstandard2.1/*.dll TimerPackage/Runtime/
        cp NetProject/bin/Release/netstandard2.1/*.pdb TimerPackage/Runtime/
        
    - name: Update package.json with tag version
      run: |
        jq --arg version "$VERSION" '.version = $version' TimerPackage/package.json > temp.json
        mv temp.json TimerPackage/package.json

    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add TimerPackage/package.json
        git add TimerPackage/Runtime/
        git diff --staged --quiet || git commit -m "Update Unity package binaries" || echo "No changes to commit"
        git push
      
    - name: Pack
      run: dotnet pack NetProject/GameTimer.csproj --configuration Release --no-build -p:Version=$VERSION --output nupkgs
      
    - name: Push to NuGet
      run: dotnet nuget push nupkgs/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
