name: Build and publish NuGet package

on:
  push:
    branches: [ main ]
    paths:
      - 'NetProject/**'
      - 'Solution/**'
      - 'UnitTest/**'
  workflow_dispatch: # This line allows manual triggering

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '7.0.x'

      - name: Restore dependencies
        run: dotnet restore Solution/GameTimer.sln

      - name: Build
        run: dotnet build Solution/GameTimer.sln --configuration Release --no-restore

      - name: Test
        run: dotnet test Solution/GameTimer.sln --no-restore --verbosity normal

      - name: Pack
        run: dotnet pack NetProject/GameTimer.csproj --configuration Release --no-build --output ./nupkgs

      - name: Publish to GitHub Packages
        run: dotnet nuget push ./nupkgs/*.nupkg --source "github" --skip-duplicate
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
